CC=g++
DEPS=Matrix.hpp
TARGET=matop
OBJS=main.cpp Matrix.cpp Add_Sub.cpp Identity_Symmetric.cpp Multiply.cpp Gaussian_Elimination.cpp Transpose.cpp LU_Decomposition.cpp DiagonallyDominant.cpp Determinant.cpp

%o: %.cpp $(DEPS)
	$(CC)